### ISSUE TITLE
All type of attributes done in input field, now need to work on CSS customization.

### ISSUE THREAD

**Issue by Git21221** [Git21221/form-snippet#1]
**Is your feature request related to a problem? Please describe.**
- If i want to set any custom color according to my choice that should be done.
- Any custom tailwind CSS should be accepted and override.

**Describe the solution you'd like**
We can use tw-merge, for custom styling we can use `sx` prop from mui.

**Describe alternatives you've considered**
No alternative.

**Additional context**
If possible, theme switching also can be done.

**Comment by ShivanshPlays** [comment]
Hi @Git21221 I have read the issue of using  use tw-merge for tailwind overriding, I think I can work on this issue if you assign it to me.

**Comment by Git21221** [comment]
@ShivanshPlays for now sx prop override the styling, but we should use className to override any custom css

**Comment by RanitDERIA** [comment]
I would like to work on this. Please assign me.

**Comment by Git21221** [comment]
@RanitDERIA already done, find something else, will update some issue now.
