### ISSUE TITLE
Add GitHub Action that automatically add labels

### ISSUE THREAD

**Issue by shubhagarwal1** [Git21221/form-snippet#13]
This task  introduces a GitHub Actions workflow to automatically label issues and pull requests based on specific keywords found in their titles or descriptions. The action checks for keywords such as "bug," "feature," "enhancement," and more, and applies the relevant labels accordingly.
please assign this task to me @Git21221

**Comment by Git21221** [comment]
@shubhagarwal1 I don't want to update readme because it's base docs, and contributors in docs isn't a good idea.

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 I don't want to update readme because it's base docs, and contributors in docs isn't a good idea.

have changed issue to requirement

**Comment by Git21221** [comment]
@shubhagarwal1 only add  "bug," "feature," "enhancement" and gssoc hacktoberfest labels
