### ISSUE TITLE
ADD TABLE OF CONTENT ON README FILE

### ISSUE THREAD

**Issue by alo7lika** [Git21221/form-snippet#37]
**Describe the bug**
A clear and concise description of what the bug is: Table of contents and API documentation are missing in the README file, which makes navigating and understanding the project more difficult for new users.

**To Reproduce**

1. Go to the repository's README file.
2. Look for the Table of Contents or API documentation section.
3. Scroll through the file to confirm the absence of these sections.
4. See error.

**Expected behavior**
The README should include a well-structured Table of Contents and detailed API documentation to help users and contributors easily navigate the file and understand the project.

**Screenshots**
No screenshots applicable.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 96.0.4664.45

**Smartphone (please complete the following information):**

- Device: iPhone 12
- OS: iOS 15
- Browser: Safari
- Version: 15.1

**Additional context**
The lack of documentation reduces the accessibility and ease of use of the project. Adding a Table of Contents and API documentation would improve the user experience.

**Comment by alo7lika** [comment]
ADD LABELS GSSOC EXT 24 AND HACKTOBERFEST
ASSIGN ME THE TASK @Git21221 
THANK YOU!

**Comment by Git21221** [comment]
@alo7lika you can add table of contents, for your more information you can check original documentation of this package
docs: https://docs-form-snippet.vercel.app/docs
we don't need to document all in readme just the starting part and Input and Button component should be fine
and there is no API documentation needed.

**Comment by alo7lika** [comment]
> @alo7lika you can add table of contents, for your more information you can check original documentation of this package docs: https://docs-form-snippet.vercel.app/docs we don't need to document all in readme just the starting part and Input and Button component should be fine and there is no API documentation needed.

OK, ADD LABELS GSSOC EXT 24 AND HACKTOBERFEST HERE ON THE ISSUE @Git21221
