### ISSUE TITLE
ADD CONTACT SECTION 

### ISSUE THREAD

**Issue by alo7lika** [Git21221/form-snippet#38]
**Describe the bug**
A clear and concise description of what the bug is: The README file is missing a Contact section and a Contributor section, making it difficult for users and contributors to get in touch or understand how to contribute to the project.

**To Reproduce**

1. Go to the repository's README file.
2. Scroll through the file to find the Contact and Contributor sections.
3. See error as these sections are missing.

**Expected behavior**
The README should include a Contact section to provide information on how users can reach out for support or feedback, and a Contributor section to guide potential contributors on how to get involved.

**Screenshots**
No screenshots applicable.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 96.0.4664.45

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S21
- OS: Android 12
- Browser: Chrome
- Version: 96.0

**Additional context**
Adding these sections would enhance communication and collaboration within the project, making it easier for both users and contributors to engage.

**Comment by alo7lika** [comment]
ADD LABELS GSSOC EXT 24 AND HACKTOBERFEST
ASSIGN ME THE TASK @Git21221
THANK YOU!

**Comment by Git21221** [comment]
@alo7lika you can add contact section but no contributors section, we are focusing the readme should be a proper small docs.

**Comment by alo7lika** [comment]
> @alo7lika you can add contact section but no contributors section, we are focusing the readme should be a proper small docs.

OK BUT ADD LABELS GSSOC EXT 24 AND HACKTOBERFEST @Git21221 HERE ON THIS ISSUE
