### ISSUE TITLE
ADD LABELS ON THE MAIN PAGE (HACKTOBERFEST)

### ISSUE THREAD

**Issue by alo7lika** [Git21221/form-snippet#39]
**Describe the bug**
LABEL NOT PRESENT ON THE MAIN PAGE, FOR THE REPO TO PARTICIPATE IN HACKTOBERFEST THE LABEL MUST BE PRESENT.

**To Reproduce**

1. Go to the repository's main page.
2. Look for the Hacktoberfest label under issues or repository settings.
3. Scroll down and check if the label is present.
4. See error – the label is missing.

**Expected behavior**
The repository should have the Hacktoberfest label visible on the main page so that it can participate in Hacktoberfest and attract contributors.

**Screenshots**
![Screenshot 2024-10-20 011605](https://github.com/user-attachments/assets/86f92e38-3efc-4200-9cee-b651d1091a5e)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 114.0.5735.134

**Smartphone (please complete the following information):**

- Device: iPhone 13
- OS: iOS 15.5
- Browser: Safari
- Version: 15.1

**Additional context**
Adding the Hacktoberfest label will ensure the repository's visibility for contributors during Hacktoberfest, encouraging more open-source contributions.

**Comment by Git21221** [comment]
@alo7lika ok I will add this

**Comment by alo7lika** [comment]
> @alo7lika ok I will add this

Yes, please unless you add the label it will not count on the hacktoberfest dashboard
![Screenshot 2024-10-20 112235](https://github.com/user-attachments/assets/2547535d-6c9e-422f-a0aa-a608d764b44d)

**Comment by Git21221** [comment]
@alo7lika can you check it once now

**Comment by alo7lika** [comment]
> @alo7lika can you check it once now

Yes, it's done now.
Thank you!
