### ISSUE TITLE
ADD Contributor Section on  the Readme

### ISSUE THREAD

**Issue by alo7lika** [Git21221/form-snippet#51]
## Description
The README currently lacks a dedicated section showcasing contributors. Adding a "Contributor" section would highlight the individuals who have contributed to the project, acknowledging their efforts and encouraging community participation.

## Solution Proposal
Implement a **Contributor Section** in the README to display a list of contributors. This section can include GitHub profile pictures, usernames, and links to individual GitHub profiles. Tools like [contrib.rocks](https://contrib.rocks) or a custom markdown table can be used for visual representation.

## Expected Outcome
- A dedicated section labeled "Our Valuable Contributors" or similar, added towards the end of the README.
- Display contributor GitHub avatars with links to their profiles.
- Encourage a sense of community and appreciation among contributors.

## Steps to Implement
1. Choose a method to display contributors (e.g., using `contrib.rocks` widget or manually created list).
2. Integrate the widget or manually update a markdown table in the README.
3. Ensure it updates automatically with new contributions or is easy to maintain.
4. Test to ensure the section looks visually appealing and works as expected.

## Additional Context
- Here's an example of how the Contributor Section can look:
  ```markdown
  ## 🌟 Our Valuable Contributors

  [![Contributors](https://contrib.rocks/image?repo=your-repo-name)](https://github.com/your-repo-name/graphs/contributors)

**Comment by alo7lika** [comment]
@Git21221 assign me the task under GSSOC EXT 24 AND HACKTOBERFEST

**Comment by Git21221** [comment]
@alo7lika I don't want to add this in readme, here readme is a documentation for primary users

**Comment by alo7lika** [comment]
> @alo7lika I don't want to add this in readme, here readme is a documentation for primary users

should I add it in the dev branch instead of main then?

**Comment by Git21221** [comment]
@alo7lika let's just not include this and close the issue
