### ISSUE TITLE
CREATE DOCUMENTATION TEMPLATE

### ISSUE THREAD

**Issue by alo7lika** [Git21221/form-snippet#60]
Here are the points for Documentation Update template:

**Is there an existing issue for this?**

I have searched the existing issues (required)

**Issue Description**

Please provide a clear description of the documentation update you are suggesting. (required)

**Suggested Change**

Provide details of the proposed change to the documentation. (required)

**Rationale**

Why is this documentation update necessary or beneficial? (optional)

**Urgency**

How urgently do you believe this documentation update is needed?
High
Medium
Low (required)

**Acknowledgements**

I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md) (required)
I'm a GSSOC'24-Extd contributor
I'm a Hacktoberfest contributor
I have starred the repository (required)
I am willing to work on this issue (optional)

![Screenshot 2024-10-27 222615](https://github.com/user-attachments/assets/7566e697-c2b1-4309-8b68-bd0d420e6b9a)

**Comment by alo7lika** [comment]
@Git21221 assign me the task under GSSOC

**Comment by Git21221** [comment]
@alo7lika why this is required?

**Comment by alo7lika** [comment]
> @alo7lika why this is required?

It brings consistency to the project, so each document—whether it's a setup guide, usage info, or API references—follows a clear, standardized structure. This makes it easier for users and contributors to find the info they need quickly.

Templates also ensure that crucial details aren’t missed because they prompt authors to include essential sections like "Overview," "Installation," and "Examples." Plus, it saves time! Contributors don’t have to start from scratch, allowing them to focus on content instead of layout. And with a consistent format, it’s simpler to keep things updated, so new users can onboard more smoothly and everyone has a clear idea of what’s happening in the project. Well-documented projects are also a lot more welcoming to potential contributors because they can understand the setup more easily, which makes for a more active and engaged community!

**Comment by Git21221** [comment]
@alo7lika and how are you gonna update it? readme or anything else?

**Comment by alo7lika** [comment]
> @alo7lika and how are you gonna update it? readme or anything else?

Will use GitHub’s “Issue and Pull Request Templates” feature, which lets us set up multiple templates for issues and PRs specifically, helping to streamline contributions. This keeps everything organized, up-to-date, and easier to navigate, especially as more features get added to the project!

**Comment by Git21221** [comment]
@alo7lika go ahead

**Comment by alo7lika** [comment]
> @alo7lika go ahead

add labels GSSOC

**Comment by Git21221** [comment]
@alo7lika doesn't matter in issue though, but I will add
